### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by allanbowe** [Boemska/user-navigator#4]
The `package-lock` file in our seed app needs the version numbers updating to avoid this warning in the public repo:

![image](https://user-images.githubusercontent.com/4420615/43145934-594428b0-8f60-11e8-9a45-ecf6f51eba7a.png)

**Comment by mlmilos** [comment]
fixed by https://github.com/Boemska/user-navigator/commit/e0009b97ff348d555866f955b26b629338e2b042
